Added the test for unit creation via API requests
gantz26/Rentzila-Cypress pull request #1
Opened 2024-10-30 17:49 UTC by gantz26

Added the test for unit creation via API requests

2024-10-31 14:11 UTC, DenysT07 requested changes

2024-10-31 14:11 UTC, DenysT07 commented on cypress/helpers/auth.api.ts
> +                    url: "https://dev.rentzila.com.ua/api/auth/jwt/create/",
Сховати URL в .env

2024-10-31 14:11 UTC, DenysT07 commented on cypress/helpers/auth.api.ts
> +    createUserAccessToken() {
Створити один метод з логіном, в який буде передаватись email і password

2024-10-31 14:11 UTC, DenysT07 commented on cypress/helpers/unit.api.ts
> +                url: "https://dev.rentzila.com.ua/api/units/",
Сховати URL в .env (для всіх решта також)
Можеш створити helper - api в якому будть зберігатись всі гетери урлів

2024-10-31 14:11 UTC, DenysT07 commented on cypress/pages/main.page.ts
> +        return cy.get("[href=\"/create-unit/\"]");
уникай екранування лапок, спробуй комбінувати різні види лапок "" '' ``

2024-10-31 14:11 UTC, DenysT07 commented on cypress/pages/main.page.ts
> +        return this.telegramPopup.find("[data-testid=\"crossIcon\"]");
Чи можеш ти використати тут це "getByTestId"?

2024-10-31 14:11 UTC, DenysT07 commented on cypress/e2e/create_unit_api.cy.ts
> +        cy.wrap(faker.word.noun({ length: { min: 10, max: 20} })).as("unitName").then(unitName => {
Створи fakerHelper який буде повертати рандомні значення, спробуй уникнути багаторівневого вкладення через wrap

2024-10-31 14:11 UTC, DenysT07 commented on cypress/e2e/create_unit_api.cy.ts
> +        mainPage.clikcProfileUnitsItem();
Виправ назву метода

2024-10-31 14:21 UTC, gantz26 commented on cypress/pages/main.page.ts
> +        return this.telegramPopup.find("[data-testid=\"crossIcon\"]");
Якщо я правильно зрозумів, то getByTestId, який то факту той же get, буде шукати у всьому DOM, а find шукає саме в елементі

2024-11-06 09:38 UTC, DenysT07 approved these changes

2024-11-06 12:32 UTC, merged